GKeymap.set("n", "<Leader>w", ":w<CR>", GQuickOpt("[W]rite file"))
GKeymap.set("n", "<Leader>W", ":wq<CR>", GQuickOpt("[*W]rite and Quit file"))
GKeymap.set("n", "<Leader>Q", ":q!<CR>", GQuickOpt("Force [Q]uit file"))
GKeymap.set("n", "<Leader>nh", ":noh<CR>", GQuickOpt("[N]o [H]ightlight"))
GKeymap.set("n", "<Leader>tv", ":vs<CR><C-w><C-w>", GQuickOpt("[T]ab split [V]ertical"))
GKeymap.set("n", "<Leader>tl", ":ls<CR>", GQuickOpt("[T]ab [L]isting"))
GKeymap.set("n", "<Leader>ts", "<C-w><C-w>", GQuickOpt("[T]ab [S]witching"))
GKeymap.set("n", "<S-Tab>", "<C-w><C-w>", GQuickOpt("[T]ab [S]witching"))
GKeymap.set("n", "<Leader>tq", "<C-w><C-q>", GQuickOpt("[T]ab [Q]uiting"))
GKeymap.set("n", "df", "lbde", GQuickOpt("[F]orward word"))
GKeymap.set("n", "<Leader>ve", "v$", GQuickOpt("[V]isual coppy to [E]nd of line"))
GKeymap.set("n", "<Leader>sn", "*", GQuickOpt("[S]earch [N]ext with hightligh"))
GKeymap.set("n", "<Leader>sN", "*:noh<CR>", GQuickOpt("[S]earch [*N]ext word"))
GKeymap.set("n", "<Leader>sp", "#", GQuickOpt("[S]earch [P]revious with hightligh"))
GKeymap.set("n", "<Leader>sP", "#:noh<CR>", GQuickOpt("[S]earch [*P]revious word"))
GKeymap.set("n", "<Leader><Leader>-", "lbi_<ESC>ea_<ESC>", GQuickOpt("[ ][-] Insert `_` at begin and end of word"))
GKeymap.set("n", "<Leader><Leader>_", "lBi_<ESC>Ea_<ESC>", GQuickOpt("[ ][_] Force insert `_` at begin and end word"))
GKeymap.set("n", "<Leader><Leader>[", "lbi[<ESC>ea]<ESC>", GQuickOpt("[ ]`[` Insert `[]] at begind and end word`"))
GKeymap.set("n", "<Leader><Leader>]", "lBi[<ESC>Ea]<ESC>", GQuickOpt("[ ]`]` Force inser `[] at begin and end word` "))
GKeymap.set("n", "<Leader><Leader>'", "lbi'<ESC>ea'<ESC>", GQuickOpt("[ ]['] Force insert `'` at begin and end word"))
GKeymap.set("n", "<Leader><Leader><", "lbi<<ESC>ea><ESC>", GQuickOpt("[ ][<] Insert `<>` at begin and end word"))
GKeymap.set("n", "<Leader><Leader>>", "lBi<<ESC>Ea><ESC>", GQuickOpt("[ ][>] Force insert `<>` at begin and end word"))
GKeymap.set("n", "<Leader>o", "jI<CR><ESC>ka<TAB>", GQuickOpt("Smart [O]pen"))
GKeymap.set("n", "<Leader><CR>", ":%s/\r//g<CR>", GQuickOpt("[CR] Smart valding file"))
GKeymap.set("n", "<C-Up>", ":m .-2<CR>==", GDfgConfig)
GKeymap.set("n", "<C-Down>", ":m .+1<CR>==", GDfgConfig)
GKeymap.set("n", "<C-k>", ":m .-2<CR>==", GDfgConfig)
GKeymap.set("n", "<C-j>", ":m .+1<CR>==", GDfgConfig)
GKeymap.set("n", "<Leader>vy", 'V"+y', GQuickOpt("Smart [V]isual [Y]anking"))
GKeymap.set("n", "<Leader>vp", 'V"+pV"+y', GQuickOpt("Smart [V]isual [P]asting"))
GKeymap.set("n", "<Leader>//", "i/**<CR>*/<ESC>0xko", GQuickOpt("[/][/] Quick comment"))
GKeymap.set("n", "<C-/>", "^i//<ESC>", GDfgConfig)
GKeymap.set("n", "<Leader>bn", ":enew<CR>", GQuickOpt("[B]uffer [N]ew"))

GKeymap.set("n", "<M-Down>", "<C-w>p<C-e><C-w>p")
GKeymap.set("n", "<M-Up>", "<C-w>p<C-y><C-w>p")
GKeymap.set("i", "<M-Down>", "<Esc><C-w>p<C-e><C-w>pi")
GKeymap.set("i", "<M-Up>", "<Esc><C-w>p<C-y><C-w>pi")
GKeymap.set("n", "<Leader>ef", "<CMD>:echo expand('%:p')<CR>", GQuickOpt('[E]cho current [F]ile path'))

--g_keymap.set('n', '<C-->', ":let g:font_size = (g:font_size - 1)<CR>:let &guifont = g:font.':h'.g:font_size <CR>:echo g:font_size<CR>")
--g_keymap.set('n', '<C-=>', ":let g:font_size = (g:font_size + 1)<CR>:let &guifont = g:font.':h'.g:font_size <CR>:echo g:font_size<CR>")

GKeymap.set("n", "<C-=>", ':exe "normal \\<C-W>>"<CR>', GDfgConfig)
GKeymap.set("n", "<C-->", ':exe "normal \\<C-W><"<CR>', GDfgConfig)
GKeymap.set("n", "<C-0>", ':exe "normal \\<C-W>=" <CR>', GDfgConfig)

GKeymap.set("i", "<C-Up>", "<ESC>:m .-2<CR>==gi", GDfgConfig)
GKeymap.set("i", "<C-Down>", "<ESC>:m .+1<CR>==gi", GDfgConfig)

GKeymap.set("v", "<C-/>", "^<C-v>I//<ESC>", GDfgConfig)
GKeymap.set("v", "<C-k>", ":m '>-2<CR>gv=gv", GDfgConfig)
GKeymap.set("v", "<C-j>", ":m '>+1<CR>gv=gv", GDfgConfig)

vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Go to previous [D]iagnostic message" })
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Go to next [D]iagnostic message" })

vim.keymap.set("n", "<leader>sf", vim.diagnostic.open_float, { desc = "[S]how [F]loating diagnostic error messages" })
vim.keymap.set("n", "<leader>qf", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uick [F]ix list" })
